'use strict';
export const GET_HIKING_TRAILS = 'GET_HIKING_TRAILS';
export const GET_HIKING_TRAILS_SUCCESS = 'GET_HIKING_TRAILS_SUCCESS';
export const GET_HIKING_TRAILS_FAIL = 'GET_HIKING_TRAILS_FAIL';

export const LOAD_MAP = 'LOAD_MAP';
export const MARKERS = 'MARKERS';

export const SHOW_WEATHER = 'SHOW_WEATHER';

export const LOCATION_DATA = 'LOCATION_DATA';
export const LOCATION_DATA_SUCCESS = 'LOCATION_DATA_SUCCESS';
export const LOCATION_DATA_FAIL = 'LOCATION_DATA_FAIL';
